language: node_js
node_js:
  - "node"
after_success:
  - 'npm i -g codecov'
  - 'nyc mocha'
  - 'nyc report --reporter=lcov'
  - 'cat ./coverage/lcov.info > coverage.lcov'
  - 'codecov'

branches:
  only:
  - master